---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ggs
  labels:
    app: ggs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggs
  template:
    metadata:
      labels:
        app: ggs
    spec:
      volumes:
      - name: ggs-data
        emptyDir: {}
      - name: config-preferences
        configMap:
          name: ggs-preferences
      - name: config-dataprep
        configMap:
          name: ggs-dataprep-script
      - name: config-datasets
        configMap:
          name: ggs-datasets
      initContainers:
      - name: ggs-dataprep-container
        image: @IMAGE_URI@
        command: ["/bin/bash"]
        args: ["/usr/local/ggs-dataprep/install.sh"]
        volumeMounts:
        - name: ggs-data
          mountPath: /usr/local/ggs-data
        - name: config-dataprep
          mountPath: /usr/local/ggs-dataprep
        - name: config-datasets
          mountPath: /usr/local/ggs-datasets
        resources:
          requests:
            cpu: 6
            memory: 20Gi
        env:
        - name: GGS_DATA
          value: /usr/local/ggs-data
        - name: SPD_LIST
          value: /usr/local/ggs-datasets
        - name: STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: azurestorageaccountname
        - name: STORAGE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: azurestoragecontainer
        - name: STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: azurestorageaccountkey
      containers:
      - name: ggs-container
        image: @IMAGE_URI@
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: ggs-data
          mountPath: /usr/local/ggs-data
        - name: config-preferences
          mountPath: /usr/local/ggs-preferences/geocodePreferences.xml
          subPath: geocodePreferences.xml
        - name: config-dataprep
          mountPath: /usr/local/ggs-dataprep
        resources:
          requests:
            cpu: 6
            memory: 20Gi
        env:
        - name: GGS_DATA
          value: /usr/local/ggs-data
        - name: GGS_PREFERENCES
          value: /usr/local/ggs-preferences/geocodePreferences.xml
        - name: _GEOSTAN_JOURNAL_FILE
          value: $(GGS_DATA)/geostan.txt
        - name: POD_CPU_LIMIT
          valueFrom:
             resourceFieldRef:
                containerName: ggs-container
                resource: limits.cpu          
      nodeSelector:
        node-app: ggs