---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ggs-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: ggs-data-pv
  storageClassName: ""