---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ggs-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: ggs-data-pv  # make sure it's a unique id in the cluster
    volumeAttributes:
      #resourceGroup: @EXISTING_RESOURCE_GROUP_NAME@  # optional, only set this when storage account is not in the same resource group as agent node
      storageAccount: @STORAGE_ACCOUNT_NAME@
      shareName: @AZURE_FILES_SHARE_NAME@  # only file share name, don't use full path
      protocol: nfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ggs-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: ggs-data-pv
  storageClassName: ""